/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.GuiElement;
import org.xtext.example.mydsl.myDsl.LayoutPositionEntry;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.PositionValue;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Layout Position Entry</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.LayoutPositionEntryImpl#getPosition <em>Position</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.LayoutPositionEntryImpl#getGuielement <em>Guielement</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LayoutPositionEntryImpl extends MinimalEObjectImpl.Container implements LayoutPositionEntry
{
  /**
   * The cached value of the '{@link #getPosition() <em>Position</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosition()
   * @generated
   * @ordered
   */
  protected PositionValue position;

  /**
   * The cached value of the '{@link #getGuielement() <em>Guielement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGuielement()
   * @generated
   * @ordered
   */
  protected GuiElement guielement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LayoutPositionEntryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.LAYOUT_POSITION_ENTRY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PositionValue getPosition()
  {
    return position;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPosition(PositionValue newPosition, NotificationChain msgs)
  {
    PositionValue oldPosition = position;
    position = newPosition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.LAYOUT_POSITION_ENTRY__POSITION, oldPosition, newPosition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPosition(PositionValue newPosition)
  {
    if (newPosition != position)
    {
      NotificationChain msgs = null;
      if (position != null)
        msgs = ((InternalEObject)position).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.LAYOUT_POSITION_ENTRY__POSITION, null, msgs);
      if (newPosition != null)
        msgs = ((InternalEObject)newPosition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.LAYOUT_POSITION_ENTRY__POSITION, null, msgs);
      msgs = basicSetPosition(newPosition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LAYOUT_POSITION_ENTRY__POSITION, newPosition, newPosition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GuiElement getGuielement()
  {
    return guielement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGuielement(GuiElement newGuielement, NotificationChain msgs)
  {
    GuiElement oldGuielement = guielement;
    guielement = newGuielement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.LAYOUT_POSITION_ENTRY__GUIELEMENT, oldGuielement, newGuielement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGuielement(GuiElement newGuielement)
  {
    if (newGuielement != guielement)
    {
      NotificationChain msgs = null;
      if (guielement != null)
        msgs = ((InternalEObject)guielement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.LAYOUT_POSITION_ENTRY__GUIELEMENT, null, msgs);
      if (newGuielement != null)
        msgs = ((InternalEObject)newGuielement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.LAYOUT_POSITION_ENTRY__GUIELEMENT, null, msgs);
      msgs = basicSetGuielement(newGuielement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LAYOUT_POSITION_ENTRY__GUIELEMENT, newGuielement, newGuielement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.LAYOUT_POSITION_ENTRY__POSITION:
        return basicSetPosition(null, msgs);
      case MyDslPackage.LAYOUT_POSITION_ENTRY__GUIELEMENT:
        return basicSetGuielement(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.LAYOUT_POSITION_ENTRY__POSITION:
        return getPosition();
      case MyDslPackage.LAYOUT_POSITION_ENTRY__GUIELEMENT:
        return getGuielement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.LAYOUT_POSITION_ENTRY__POSITION:
        setPosition((PositionValue)newValue);
        return;
      case MyDslPackage.LAYOUT_POSITION_ENTRY__GUIELEMENT:
        setGuielement((GuiElement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.LAYOUT_POSITION_ENTRY__POSITION:
        setPosition((PositionValue)null);
        return;
      case MyDslPackage.LAYOUT_POSITION_ENTRY__GUIELEMENT:
        setGuielement((GuiElement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.LAYOUT_POSITION_ENTRY__POSITION:
        return position != null;
      case MyDslPackage.LAYOUT_POSITION_ENTRY__GUIELEMENT:
        return guielement != null;
    }
    return super.eIsSet(featureID);
  }

} //LayoutPositionEntryImpl
