/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fixed</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Fixed#getFixed <em>Fixed</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFixed()
 * @model
 * @generated
 */
public interface Fixed extends EObject
{
  /**
   * Returns the value of the '<em><b>Fixed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fixed</em>' attribute.
   * @see #setFixed(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFixed_Fixed()
   * @model
   * @generated
   */
  int getFixed();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Fixed#getFixed <em>Fixed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fixed</em>' attribute.
   * @see #getFixed()
   * @generated
   */
  void setFixed(int value);

} // Fixed
