/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Layout Horizontal Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.LayoutHorizontalEntry#getSpace <em>Space</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.LayoutHorizontalEntry#getGuielement <em>Guielement</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayoutHorizontalEntry()
 * @model
 * @generated
 */
public interface LayoutHorizontalEntry extends EObject
{
  /**
   * Returns the value of the '<em><b>Space</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Space</em>' containment reference.
   * @see #setSpace(Space)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayoutHorizontalEntry_Space()
   * @model containment="true"
   * @generated
   */
  Space getSpace();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.LayoutHorizontalEntry#getSpace <em>Space</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Space</em>' containment reference.
   * @see #getSpace()
   * @generated
   */
  void setSpace(Space value);

  /**
   * Returns the value of the '<em><b>Guielement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guielement</em>' containment reference.
   * @see #setGuielement(GuiElement)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayoutHorizontalEntry_Guielement()
   * @model containment="true"
   * @generated
   */
  GuiElement getGuielement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.LayoutHorizontalEntry#getGuielement <em>Guielement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Guielement</em>' containment reference.
   * @see #getGuielement()
   * @generated
   */
  void setGuielement(GuiElement value);

} // LayoutHorizontalEntry
