/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DomainmodelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDomainmodel()
   * @generated
   */
  int DOMAINMODEL = 0;

  /**
   * The feature id for the '<em><b>Main</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL__MAIN = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Domainmodel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TypeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__SIZE = 1;

  /**
   * The feature id for the '<em><b>Layout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__LAYOUT = 2;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FrameImpl <em>Frame</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FrameImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFrame()
   * @generated
   */
  int FRAME = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__SIZE = TYPE__SIZE;

  /**
   * The feature id for the '<em><b>Layout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__LAYOUT = TYPE__LAYOUT;

  /**
   * The number of structural features of the '<em>Frame</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ContainerImpl <em>Container</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ContainerImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getContainer()
   * @generated
   */
  int CONTAINER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__SIZE = TYPE__SIZE;

  /**
   * The feature id for the '<em><b>Layout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__LAYOUT = TYPE__LAYOUT;

  /**
   * The number of structural features of the '<em>Container</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.GuiElementImpl <em>Gui Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.GuiElementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGuiElement()
   * @generated
   */
  int GUI_ELEMENT = 15;

  /**
   * The number of structural features of the '<em>Gui Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutImpl <em>Layout</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LayoutImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayout()
   * @generated
   */
  int LAYOUT = 4;

  /**
   * The number of structural features of the '<em>Layout</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_FEATURE_COUNT = GUI_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutHorizontalImpl <em>Layout Horizontal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LayoutHorizontalImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayoutHorizontal()
   * @generated
   */
  int LAYOUT_HORIZONTAL = 5;

  /**
   * The feature id for the '<em><b>Fixed</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_HORIZONTAL__FIXED = LAYOUT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_HORIZONTAL__ENTRIES = LAYOUT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Layout Horizontal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_HORIZONTAL_FEATURE_COUNT = LAYOUT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutHorizontalEntryImpl <em>Layout Horizontal Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LayoutHorizontalEntryImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayoutHorizontalEntry()
   * @generated
   */
  int LAYOUT_HORIZONTAL_ENTRY = 6;

  /**
   * The feature id for the '<em><b>Space</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_HORIZONTAL_ENTRY__SPACE = 0;

  /**
   * The feature id for the '<em><b>Guielement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_HORIZONTAL_ENTRY__GUIELEMENT = 1;

  /**
   * The number of structural features of the '<em>Layout Horizontal Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_HORIZONTAL_ENTRY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutVerticalImpl <em>Layout Vertical</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LayoutVerticalImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayoutVertical()
   * @generated
   */
  int LAYOUT_VERTICAL = 7;

  /**
   * The feature id for the '<em><b>Fixed</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_VERTICAL__FIXED = LAYOUT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_VERTICAL__ENTRIES = LAYOUT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Layout Vertical</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_VERTICAL_FEATURE_COUNT = LAYOUT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutVerticalEntryImpl <em>Layout Vertical Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LayoutVerticalEntryImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayoutVerticalEntry()
   * @generated
   */
  int LAYOUT_VERTICAL_ENTRY = 8;

  /**
   * The feature id for the '<em><b>Space</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_VERTICAL_ENTRY__SPACE = 0;

  /**
   * The feature id for the '<em><b>Guielement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_VERTICAL_ENTRY__GUIELEMENT = 1;

  /**
   * The number of structural features of the '<em>Layout Vertical Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_VERTICAL_ENTRY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutPositionImpl <em>Layout Position</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LayoutPositionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayoutPosition()
   * @generated
   */
  int LAYOUT_POSITION = 9;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_POSITION__ENTRIES = LAYOUT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Layout Position</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_POSITION_FEATURE_COUNT = LAYOUT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutPositionEntryImpl <em>Layout Position Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LayoutPositionEntryImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayoutPositionEntry()
   * @generated
   */
  int LAYOUT_POSITION_ENTRY = 10;

  /**
   * The feature id for the '<em><b>Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_POSITION_ENTRY__POSITION = 0;

  /**
   * The feature id for the '<em><b>Guielement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_POSITION_ENTRY__GUIELEMENT = 1;

  /**
   * The number of structural features of the '<em>Layout Position Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_POSITION_ENTRY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FixedImpl <em>Fixed</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FixedImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFixed()
   * @generated
   */
  int FIXED = 11;

  /**
   * The feature id for the '<em><b>Fixed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIXED__FIXED = 0;

  /**
   * The number of structural features of the '<em>Fixed</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIXED_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SpaceImpl <em>Space</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SpaceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSpace()
   * @generated
   */
  int SPACE = 12;

  /**
   * The feature id for the '<em><b>Space</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPACE__SPACE = 0;

  /**
   * The number of structural features of the '<em>Space</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPACE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.PositionValueImpl <em>Position Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.PositionValueImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPositionValue()
   * @generated
   */
  int POSITION_VALUE = 13;

  /**
   * The feature id for the '<em><b>Pos X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSITION_VALUE__POS_X = 0;

  /**
   * The feature id for the '<em><b>Pos Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSITION_VALUE__POS_Y = 1;

  /**
   * The number of structural features of the '<em>Position Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSITION_VALUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SizeImpl <em>Size</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SizeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSize()
   * @generated
   */
  int SIZE = 14;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE__WIDTH = 0;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE__HEIGHT = 1;

  /**
   * The number of structural features of the '<em>Size</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ContainerReferenceImpl <em>Container Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ContainerReferenceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getContainerReference()
   * @generated
   */
  int CONTAINER_REFERENCE = 16;

  /**
   * The feature id for the '<em><b>Reference Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_REFERENCE__REFERENCE_NAME = GUI_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_REFERENCE__NAME = GUI_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Container Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_REFERENCE_FEATURE_COUNT = GUI_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TextImpl <em>Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TextImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getText()
   * @generated
   */
  int TEXT = 17;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__TEXT = 0;

  /**
   * The number of structural features of the '<em>Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TextfieldImpl <em>Textfield</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TextfieldImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTextfield()
   * @generated
   */
  int TEXTFIELD = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXTFIELD__NAME = GUI_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXTFIELD__SIZE = GUI_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXTFIELD__TEXT = GUI_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Textfield</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXTFIELD_FEATURE_COUNT = GUI_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LabelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLabel()
   * @generated
   */
  int LABEL = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__NAME = GUI_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__SIZE = GUI_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__TEXT = GUI_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = GUI_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ButtonImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getButton()
   * @generated
   */
  int BUTTON = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__NAME = GUI_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__SIZE = GUI_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__TEXT = GUI_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = GUI_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CheckboxImpl <em>Checkbox</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CheckboxImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCheckbox()
   * @generated
   */
  int CHECKBOX = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX__NAME = GUI_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX__SIZE = GUI_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Checked</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX__CHECKED = GUI_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX__TEXT = GUI_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Checkbox</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX_FEATURE_COUNT = GUI_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RadiobuttonImpl <em>Radiobutton</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RadiobuttonImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRadiobutton()
   * @generated
   */
  int RADIOBUTTON = 22;

  /**
   * The feature id for the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIOBUTTON__GROUP = GUI_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIOBUTTON__NAME = GUI_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIOBUTTON__SIZE = GUI_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Checked</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIOBUTTON__CHECKED = GUI_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIOBUTTON__TEXT = GUI_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Radiobutton</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIOBUTTON_FEATURE_COUNT = GUI_ELEMENT_FEATURE_COUNT + 5;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Domainmodel <em>Domainmodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domainmodel</em>'.
   * @see org.xtext.example.mydsl.myDsl.Domainmodel
   * @generated
   */
  EClass getDomainmodel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Domainmodel#getMain <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Main</em>'.
   * @see org.xtext.example.mydsl.myDsl.Domainmodel#getMain()
   * @see #getDomainmodel()
   * @generated
   */
  EAttribute getDomainmodel_Main();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Domainmodel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.myDsl.Domainmodel#getElements()
   * @see #getDomainmodel()
   * @generated
   */
  EReference getDomainmodel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Type#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see org.xtext.example.mydsl.myDsl.Type#getSize()
   * @see #getType()
   * @generated
   */
  EReference getType_Size();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Type#getLayout <em>Layout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Layout</em>'.
   * @see org.xtext.example.mydsl.myDsl.Type#getLayout()
   * @see #getType()
   * @generated
   */
  EReference getType_Layout();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Frame <em>Frame</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Frame</em>'.
   * @see org.xtext.example.mydsl.myDsl.Frame
   * @generated
   */
  EClass getFrame();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Container <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Container</em>'.
   * @see org.xtext.example.mydsl.myDsl.Container
   * @generated
   */
  EClass getContainer();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Layout <em>Layout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout</em>'.
   * @see org.xtext.example.mydsl.myDsl.Layout
   * @generated
   */
  EClass getLayout();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.LayoutHorizontal <em>Layout Horizontal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout Horizontal</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutHorizontal
   * @generated
   */
  EClass getLayoutHorizontal();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.LayoutHorizontal#getFixed <em>Fixed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fixed</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutHorizontal#getFixed()
   * @see #getLayoutHorizontal()
   * @generated
   */
  EReference getLayoutHorizontal_Fixed();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.LayoutHorizontal#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutHorizontal#getEntries()
   * @see #getLayoutHorizontal()
   * @generated
   */
  EReference getLayoutHorizontal_Entries();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.LayoutHorizontalEntry <em>Layout Horizontal Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout Horizontal Entry</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutHorizontalEntry
   * @generated
   */
  EClass getLayoutHorizontalEntry();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.LayoutHorizontalEntry#getSpace <em>Space</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Space</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutHorizontalEntry#getSpace()
   * @see #getLayoutHorizontalEntry()
   * @generated
   */
  EReference getLayoutHorizontalEntry_Space();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.LayoutHorizontalEntry#getGuielement <em>Guielement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Guielement</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutHorizontalEntry#getGuielement()
   * @see #getLayoutHorizontalEntry()
   * @generated
   */
  EReference getLayoutHorizontalEntry_Guielement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.LayoutVertical <em>Layout Vertical</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout Vertical</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutVertical
   * @generated
   */
  EClass getLayoutVertical();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.LayoutVertical#getFixed <em>Fixed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fixed</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutVertical#getFixed()
   * @see #getLayoutVertical()
   * @generated
   */
  EReference getLayoutVertical_Fixed();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.LayoutVertical#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutVertical#getEntries()
   * @see #getLayoutVertical()
   * @generated
   */
  EReference getLayoutVertical_Entries();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.LayoutVerticalEntry <em>Layout Vertical Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout Vertical Entry</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutVerticalEntry
   * @generated
   */
  EClass getLayoutVerticalEntry();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.LayoutVerticalEntry#getSpace <em>Space</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Space</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutVerticalEntry#getSpace()
   * @see #getLayoutVerticalEntry()
   * @generated
   */
  EReference getLayoutVerticalEntry_Space();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.LayoutVerticalEntry#getGuielement <em>Guielement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Guielement</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutVerticalEntry#getGuielement()
   * @see #getLayoutVerticalEntry()
   * @generated
   */
  EReference getLayoutVerticalEntry_Guielement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.LayoutPosition <em>Layout Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout Position</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutPosition
   * @generated
   */
  EClass getLayoutPosition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.LayoutPosition#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutPosition#getEntries()
   * @see #getLayoutPosition()
   * @generated
   */
  EReference getLayoutPosition_Entries();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.LayoutPositionEntry <em>Layout Position Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout Position Entry</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutPositionEntry
   * @generated
   */
  EClass getLayoutPositionEntry();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.LayoutPositionEntry#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Position</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutPositionEntry#getPosition()
   * @see #getLayoutPositionEntry()
   * @generated
   */
  EReference getLayoutPositionEntry_Position();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.LayoutPositionEntry#getGuielement <em>Guielement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Guielement</em>'.
   * @see org.xtext.example.mydsl.myDsl.LayoutPositionEntry#getGuielement()
   * @see #getLayoutPositionEntry()
   * @generated
   */
  EReference getLayoutPositionEntry_Guielement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Fixed <em>Fixed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fixed</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fixed
   * @generated
   */
  EClass getFixed();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Fixed#getFixed <em>Fixed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fixed</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fixed#getFixed()
   * @see #getFixed()
   * @generated
   */
  EAttribute getFixed_Fixed();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Space <em>Space</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Space</em>'.
   * @see org.xtext.example.mydsl.myDsl.Space
   * @generated
   */
  EClass getSpace();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Space#getSpace <em>Space</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Space</em>'.
   * @see org.xtext.example.mydsl.myDsl.Space#getSpace()
   * @see #getSpace()
   * @generated
   */
  EAttribute getSpace_Space();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.PositionValue <em>Position Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Position Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.PositionValue
   * @generated
   */
  EClass getPositionValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.PositionValue#getPosX <em>Pos X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pos X</em>'.
   * @see org.xtext.example.mydsl.myDsl.PositionValue#getPosX()
   * @see #getPositionValue()
   * @generated
   */
  EAttribute getPositionValue_PosX();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.PositionValue#getPosY <em>Pos Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pos Y</em>'.
   * @see org.xtext.example.mydsl.myDsl.PositionValue#getPosY()
   * @see #getPositionValue()
   * @generated
   */
  EAttribute getPositionValue_PosY();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Size <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Size</em>'.
   * @see org.xtext.example.mydsl.myDsl.Size
   * @generated
   */
  EClass getSize();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Size#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see org.xtext.example.mydsl.myDsl.Size#getWidth()
   * @see #getSize()
   * @generated
   */
  EAttribute getSize_Width();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Size#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see org.xtext.example.mydsl.myDsl.Size#getHeight()
   * @see #getSize()
   * @generated
   */
  EAttribute getSize_Height();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.GuiElement <em>Gui Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gui Element</em>'.
   * @see org.xtext.example.mydsl.myDsl.GuiElement
   * @generated
   */
  EClass getGuiElement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ContainerReference <em>Container Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Container Reference</em>'.
   * @see org.xtext.example.mydsl.myDsl.ContainerReference
   * @generated
   */
  EClass getContainerReference();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ContainerReference#getReferenceName <em>Reference Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reference Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.ContainerReference#getReferenceName()
   * @see #getContainerReference()
   * @generated
   */
  EAttribute getContainerReference_ReferenceName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ContainerReference#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.ContainerReference#getName()
   * @see #getContainerReference()
   * @generated
   */
  EAttribute getContainerReference_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text</em>'.
   * @see org.xtext.example.mydsl.myDsl.Text
   * @generated
   */
  EClass getText();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Text#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.mydsl.myDsl.Text#getText()
   * @see #getText()
   * @generated
   */
  EAttribute getText_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Textfield <em>Textfield</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Textfield</em>'.
   * @see org.xtext.example.mydsl.myDsl.Textfield
   * @generated
   */
  EClass getTextfield();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Textfield#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Textfield#getName()
   * @see #getTextfield()
   * @generated
   */
  EAttribute getTextfield_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Textfield#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see org.xtext.example.mydsl.myDsl.Textfield#getSize()
   * @see #getTextfield()
   * @generated
   */
  EReference getTextfield_Size();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Textfield#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.mydsl.myDsl.Textfield#getText()
   * @see #getTextfield()
   * @generated
   */
  EReference getTextfield_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see org.xtext.example.mydsl.myDsl.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Label#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Label#getName()
   * @see #getLabel()
   * @generated
   */
  EAttribute getLabel_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Label#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see org.xtext.example.mydsl.myDsl.Label#getSize()
   * @see #getLabel()
   * @generated
   */
  EReference getLabel_Size();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Label#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.mydsl.myDsl.Label#getText()
   * @see #getLabel()
   * @generated
   */
  EReference getLabel_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see org.xtext.example.mydsl.myDsl.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Button#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Button#getName()
   * @see #getButton()
   * @generated
   */
  EAttribute getButton_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Button#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see org.xtext.example.mydsl.myDsl.Button#getSize()
   * @see #getButton()
   * @generated
   */
  EReference getButton_Size();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Button#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.mydsl.myDsl.Button#getText()
   * @see #getButton()
   * @generated
   */
  EReference getButton_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Checkbox <em>Checkbox</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Checkbox</em>'.
   * @see org.xtext.example.mydsl.myDsl.Checkbox
   * @generated
   */
  EClass getCheckbox();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Checkbox#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Checkbox#getName()
   * @see #getCheckbox()
   * @generated
   */
  EAttribute getCheckbox_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Checkbox#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see org.xtext.example.mydsl.myDsl.Checkbox#getSize()
   * @see #getCheckbox()
   * @generated
   */
  EReference getCheckbox_Size();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Checkbox#getChecked <em>Checked</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Checked</em>'.
   * @see org.xtext.example.mydsl.myDsl.Checkbox#getChecked()
   * @see #getCheckbox()
   * @generated
   */
  EAttribute getCheckbox_Checked();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Checkbox#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.mydsl.myDsl.Checkbox#getText()
   * @see #getCheckbox()
   * @generated
   */
  EReference getCheckbox_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Radiobutton <em>Radiobutton</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Radiobutton</em>'.
   * @see org.xtext.example.mydsl.myDsl.Radiobutton
   * @generated
   */
  EClass getRadiobutton();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Radiobutton#getGroup <em>Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Group</em>'.
   * @see org.xtext.example.mydsl.myDsl.Radiobutton#getGroup()
   * @see #getRadiobutton()
   * @generated
   */
  EAttribute getRadiobutton_Group();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Radiobutton#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Radiobutton#getName()
   * @see #getRadiobutton()
   * @generated
   */
  EAttribute getRadiobutton_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Radiobutton#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see org.xtext.example.mydsl.myDsl.Radiobutton#getSize()
   * @see #getRadiobutton()
   * @generated
   */
  EReference getRadiobutton_Size();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Radiobutton#getChecked <em>Checked</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Checked</em>'.
   * @see org.xtext.example.mydsl.myDsl.Radiobutton#getChecked()
   * @see #getRadiobutton()
   * @generated
   */
  EAttribute getRadiobutton_Checked();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Radiobutton#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.mydsl.myDsl.Radiobutton#getText()
   * @see #getRadiobutton()
   * @generated
   */
  EReference getRadiobutton_Text();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DomainmodelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDomainmodel()
     * @generated
     */
    EClass DOMAINMODEL = eINSTANCE.getDomainmodel();

    /**
     * The meta object literal for the '<em><b>Main</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOMAINMODEL__MAIN = eINSTANCE.getDomainmodel_Main();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAINMODEL__ELEMENTS = eINSTANCE.getDomainmodel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TypeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__SIZE = eINSTANCE.getType_Size();

    /**
     * The meta object literal for the '<em><b>Layout</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__LAYOUT = eINSTANCE.getType_Layout();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FrameImpl <em>Frame</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FrameImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFrame()
     * @generated
     */
    EClass FRAME = eINSTANCE.getFrame();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ContainerImpl <em>Container</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ContainerImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getContainer()
     * @generated
     */
    EClass CONTAINER = eINSTANCE.getContainer();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutImpl <em>Layout</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LayoutImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayout()
     * @generated
     */
    EClass LAYOUT = eINSTANCE.getLayout();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutHorizontalImpl <em>Layout Horizontal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LayoutHorizontalImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayoutHorizontal()
     * @generated
     */
    EClass LAYOUT_HORIZONTAL = eINSTANCE.getLayoutHorizontal();

    /**
     * The meta object literal for the '<em><b>Fixed</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_HORIZONTAL__FIXED = eINSTANCE.getLayoutHorizontal_Fixed();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_HORIZONTAL__ENTRIES = eINSTANCE.getLayoutHorizontal_Entries();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutHorizontalEntryImpl <em>Layout Horizontal Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LayoutHorizontalEntryImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayoutHorizontalEntry()
     * @generated
     */
    EClass LAYOUT_HORIZONTAL_ENTRY = eINSTANCE.getLayoutHorizontalEntry();

    /**
     * The meta object literal for the '<em><b>Space</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_HORIZONTAL_ENTRY__SPACE = eINSTANCE.getLayoutHorizontalEntry_Space();

    /**
     * The meta object literal for the '<em><b>Guielement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_HORIZONTAL_ENTRY__GUIELEMENT = eINSTANCE.getLayoutHorizontalEntry_Guielement();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutVerticalImpl <em>Layout Vertical</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LayoutVerticalImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayoutVertical()
     * @generated
     */
    EClass LAYOUT_VERTICAL = eINSTANCE.getLayoutVertical();

    /**
     * The meta object literal for the '<em><b>Fixed</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_VERTICAL__FIXED = eINSTANCE.getLayoutVertical_Fixed();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_VERTICAL__ENTRIES = eINSTANCE.getLayoutVertical_Entries();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutVerticalEntryImpl <em>Layout Vertical Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LayoutVerticalEntryImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayoutVerticalEntry()
     * @generated
     */
    EClass LAYOUT_VERTICAL_ENTRY = eINSTANCE.getLayoutVerticalEntry();

    /**
     * The meta object literal for the '<em><b>Space</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_VERTICAL_ENTRY__SPACE = eINSTANCE.getLayoutVerticalEntry_Space();

    /**
     * The meta object literal for the '<em><b>Guielement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_VERTICAL_ENTRY__GUIELEMENT = eINSTANCE.getLayoutVerticalEntry_Guielement();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutPositionImpl <em>Layout Position</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LayoutPositionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayoutPosition()
     * @generated
     */
    EClass LAYOUT_POSITION = eINSTANCE.getLayoutPosition();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_POSITION__ENTRIES = eINSTANCE.getLayoutPosition_Entries();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LayoutPositionEntryImpl <em>Layout Position Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LayoutPositionEntryImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayoutPositionEntry()
     * @generated
     */
    EClass LAYOUT_POSITION_ENTRY = eINSTANCE.getLayoutPositionEntry();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_POSITION_ENTRY__POSITION = eINSTANCE.getLayoutPositionEntry_Position();

    /**
     * The meta object literal for the '<em><b>Guielement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_POSITION_ENTRY__GUIELEMENT = eINSTANCE.getLayoutPositionEntry_Guielement();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FixedImpl <em>Fixed</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FixedImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFixed()
     * @generated
     */
    EClass FIXED = eINSTANCE.getFixed();

    /**
     * The meta object literal for the '<em><b>Fixed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIXED__FIXED = eINSTANCE.getFixed_Fixed();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SpaceImpl <em>Space</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SpaceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSpace()
     * @generated
     */
    EClass SPACE = eINSTANCE.getSpace();

    /**
     * The meta object literal for the '<em><b>Space</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPACE__SPACE = eINSTANCE.getSpace_Space();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.PositionValueImpl <em>Position Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.PositionValueImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPositionValue()
     * @generated
     */
    EClass POSITION_VALUE = eINSTANCE.getPositionValue();

    /**
     * The meta object literal for the '<em><b>Pos X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POSITION_VALUE__POS_X = eINSTANCE.getPositionValue_PosX();

    /**
     * The meta object literal for the '<em><b>Pos Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POSITION_VALUE__POS_Y = eINSTANCE.getPositionValue_PosY();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SizeImpl <em>Size</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SizeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSize()
     * @generated
     */
    EClass SIZE = eINSTANCE.getSize();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE__WIDTH = eINSTANCE.getSize_Width();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE__HEIGHT = eINSTANCE.getSize_Height();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.GuiElementImpl <em>Gui Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.GuiElementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGuiElement()
     * @generated
     */
    EClass GUI_ELEMENT = eINSTANCE.getGuiElement();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ContainerReferenceImpl <em>Container Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ContainerReferenceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getContainerReference()
     * @generated
     */
    EClass CONTAINER_REFERENCE = eINSTANCE.getContainerReference();

    /**
     * The meta object literal for the '<em><b>Reference Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTAINER_REFERENCE__REFERENCE_NAME = eINSTANCE.getContainerReference_ReferenceName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTAINER_REFERENCE__NAME = eINSTANCE.getContainerReference_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TextImpl <em>Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TextImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getText()
     * @generated
     */
    EClass TEXT = eINSTANCE.getText();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__TEXT = eINSTANCE.getText_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TextfieldImpl <em>Textfield</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TextfieldImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTextfield()
     * @generated
     */
    EClass TEXTFIELD = eINSTANCE.getTextfield();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXTFIELD__NAME = eINSTANCE.getTextfield_Name();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXTFIELD__SIZE = eINSTANCE.getTextfield_Size();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXTFIELD__TEXT = eINSTANCE.getTextfield_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LabelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABEL__NAME = eINSTANCE.getLabel_Name();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABEL__SIZE = eINSTANCE.getLabel_Size();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABEL__TEXT = eINSTANCE.getLabel_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ButtonImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUTTON__NAME = eINSTANCE.getButton_Name();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUTTON__SIZE = eINSTANCE.getButton_Size();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUTTON__TEXT = eINSTANCE.getButton_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CheckboxImpl <em>Checkbox</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CheckboxImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCheckbox()
     * @generated
     */
    EClass CHECKBOX = eINSTANCE.getCheckbox();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECKBOX__NAME = eINSTANCE.getCheckbox_Name();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECKBOX__SIZE = eINSTANCE.getCheckbox_Size();

    /**
     * The meta object literal for the '<em><b>Checked</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECKBOX__CHECKED = eINSTANCE.getCheckbox_Checked();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECKBOX__TEXT = eINSTANCE.getCheckbox_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RadiobuttonImpl <em>Radiobutton</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RadiobuttonImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRadiobutton()
     * @generated
     */
    EClass RADIOBUTTON = eINSTANCE.getRadiobutton();

    /**
     * The meta object literal for the '<em><b>Group</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RADIOBUTTON__GROUP = eINSTANCE.getRadiobutton_Group();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RADIOBUTTON__NAME = eINSTANCE.getRadiobutton_Name();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RADIOBUTTON__SIZE = eINSTANCE.getRadiobutton_Size();

    /**
     * The meta object literal for the '<em><b>Checked</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RADIOBUTTON__CHECKED = eINSTANCE.getRadiobutton_Checked();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RADIOBUTTON__TEXT = eINSTANCE.getRadiobutton_Text();

  }

} //MyDslPackage
