/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Position Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PositionValue#getPosX <em>Pos X</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PositionValue#getPosY <em>Pos Y</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPositionValue()
 * @model
 * @generated
 */
public interface PositionValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Pos X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pos X</em>' attribute.
   * @see #setPosX(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPositionValue_PosX()
   * @model
   * @generated
   */
  int getPosX();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PositionValue#getPosX <em>Pos X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pos X</em>' attribute.
   * @see #getPosX()
   * @generated
   */
  void setPosX(int value);

  /**
   * Returns the value of the '<em><b>Pos Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pos Y</em>' attribute.
   * @see #setPosY(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPositionValue_PosY()
   * @model
   * @generated
   */
  int getPosY();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PositionValue#getPosY <em>Pos Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pos Y</em>' attribute.
   * @see #getPosY()
   * @generated
   */
  void setPosY(int value);

} // PositionValue
